<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="System.IO" />
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SciCanvas.App\SciCanvas.App.csproj" />
    <ProjectReference Include="..\..\src\SciCanvas.Cli\SciCanvas.Cli.csproj" />
    <ProjectReference Include="..\..\src\SciCanvas.Core\SciCanvas.Core.csproj" />
    <ProjectReference Include="..\..\src\SciCanvas.Imaging\SciCanvas.Imaging.csproj" />
    <ProjectReference Include="..\..\src\SciCanvas.Platform.Windows\SciCanvas.Platform.Windows.csproj" />
  </ItemGroup>

</Project>
